# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_for', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_for', models.CharField(default=True, max_length=50)),
                ('question_one', models.CharField(default=True, max_length=100)),
                ('question_two', models.CharField(default=True, max_length=100)),
                ('question_three', models.CharField(default=True, max_length=100)),
                ('question_four', models.CharField(default=True, max_length=100)),
                ('question_five', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_location', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jobopening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_created', models.DateTimeField(auto_created=True, null=True)),
                ('job_title', models.CharField(max_length=50, verbose_name='Designation')),
                ('slug', models.SlugField(max_length=40)),
                ('job_location_sample', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=20, null=True, verbose_name='Sample Job Location')),
                ('experience', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Experience')),
                ('skill', models.CharField(max_length=100, verbose_name='Skills')),
                ('qualification', models.CharField(choices=[('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100, verbose_name='Qualification')),
                ('salary_budget', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Salary Criteria')),
                ('referral_reward', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Referral Amount')),
                ('industry', models.CharField(max_length=50, verbose_name='Industry')),
                ('functional_area', models.CharField(choices=[('Accounting / Tax / Company', 'Accounting / Tax / Company'), ('Secretary / Auditing', 'Secretary / Auditing'), ('Agent', 'Agent'), ('Airlines / Ticketing / Travel / Reservation', 'Airlines / Ticketing / Travel / Reservation'), ('Analytics / Business Intelligences', 'Analytics / Business Intelligences'), ('Anchoring / TV / Films / Production', 'Anchoring / TV / Films / Production'), ('Architecture / Interior', 'Architecture / Interior'), ('Art Director/Web Design/ Graphic', 'Art Director/Web Design/ Graphic'), ('Banking / Insurance', 'Banking / Insurance'), ('Content / Editor / Generalist', 'Content / Editor / Generalist'), ('Corporate Planning / Consulting / Strategy', 'Corporate Planning / Consulting / Strategy'), ('Entrepreneur / Businessman/ Outside Management Consultant', 'Entrepreneur / Businessman/ Outside Management Consultant'), ('Import / Export', 'Import / Export'), ('Fashion', 'Fashion'), ('Front Office/Secretarial/Computer Operator', 'Front Office/Secretarial/Computer Operator'), ('Hotels/ Restaurant Manager', 'Hotels/ Restaurant Manager'), ('HR/Admin/PM/IT/Training', 'HR/Admin/PM/IT/Training'), ('ITES/BPO/Tele calling/Operations/ Customer Service', 'ITES/BPO/Tele calling/Operations/ Customer Service'), ('Legal /Law', 'Legal /Law'), ('Medical Professional/ Technician/ Healthcare Specialist', 'Medical Professional/ Technician/ Healthcare Specialist'), ('Mktg/Advtg/MR/Media Planning/PR/ Corp. Panning', 'Mktg/Advtg/MR/Media Planning/PR/Corp. Panning'), ('Packaging Development', 'Packaging Development'), ('Production/ Service Engineering/Manufacturing / Maintenance', 'Production/ Service Engineering/Manufacturing / Maintenance'), ('Project Management/Site Engineers', 'Project Management/Site Engineers'), ('Purchase/SCM', 'Purchase/SCM'), ('R&D/Engineering Design', 'R&D/Engineering Design'), ('Sales / Business Development / Client servicing', 'Sales / Business Development / Client servicing'), ('Security', 'Security'), ('Shipping', 'Shipping'), ('Software Development - ALL', 'Software Development - ALL'), ('Teaching / Education / Language Specialist', 'Teaching / Education / Language Specialist'), ('Telecom / IT Hardware / Tech. staff /Support', 'Telecom / IT Hardware / Tech. staff /Support'), ('Top Management', 'Top Management'), ('Any Other', 'Any Other')], max_length=100, verbose_name='Functional Area')),
                ('role_category', models.CharField(max_length=50, verbose_name='Role Category')),
                ('employment_type', models.CharField(max_length=50, verbose_name='Employment Type')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('nice_to_have', models.CharField(max_length=500, null=True, verbose_name='Nice To Have')),
                ('active', models.BooleanField(default=True)),
                ('Questions', models.ManyToManyField(default=None, to='jobopening.ApplicationQuestions', verbose_name='Application Questionnaires')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.CompanyProfile', verbose_name='Company Name')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobopening.JobLocation', verbose_name='Job Location')),
            ],
            options={
                'ordering': ['-job_created'],
            },
        ),
        migrations.AddField(
            model_name='jobapply',
            name='title',
            field=models.ForeignKey(default=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='jobopening.Jobopening'),
        ),
    ]
