FUNCTIONAL_AREA_CHOICES = (
    ("Accounting / Tax / Company", "Accounting / Tax / Company"),
    ("Secretary / Auditing", "Secretary / Auditing"),
    ("Agent", "Agent"),
    ("Airlines / Ticketing / Travel / Reservation", "Airlines / Ticketing / Travel / Reservation"),
    ("Analytics / Business Intelligences", "Analytics / Business Intelligences"),
    ("Anchoring / TV / Films / Production", "Anchoring / TV / Films / Production"),
    ("Architecture / Interior", "Architecture / Interior"),
    ("Art Director/Web Design/ Graphic", "Art Director/Web Design/ Graphic"),
    ("Banking / Insurance", "Banking / Insurance"),
    ("Content / Editor / Generalist", "Content / Editor / Generalist"),
    ("Corporate Planning / Consulting / Strategy", "Corporate Planning / Consulting / Strategy"),
    ("Entrepreneur / Businessman/ Outside Management Consultant", "Entrepreneur / Businessman/ Outside Management "
                                                                  "Consultant"),
    ("Import / Export", "Import / Export"),
    ("Fashion", "Fashion"),
    ("Front Office/Secretarial/Computer Operator", "Front Office/Secretarial/Computer Operator"),
    ("Hotels/ Restaurant Manager", "Hotels/ Restaurant Manager"),
    ("HR/Admin/PM/IT/Training", "HR/Admin/PM/IT/Training"),
    ("ITES/BPO/Tele calling/Operations/ Customer Service", "ITES/BPO/Tele calling/Operations/ Customer Service"),
    ("Legal /Law", "Legal /Law"),
    ("Medical Professional/ Technician/ Healthcare Specialist", "Medical Professional/ Technician/ Healthcare "
                                                                "Specialist"),
    ("Mktg/Advtg/MR/Media Planning/PR/ Corp. Panning", "Mktg/Advtg/MR/Media Planning/PR/Corp. Panning"),
    ("Packaging Development", "Packaging Development"),
    ("Production/ Service Engineering/Manufacturing / Maintenance", "Production/ Service Engineering/Manufacturing / "
                                                                    "Maintenance"),
    ("Project Management/Site Engineers", "Project Management/Site Engineers"),
    ("Purchase/SCM", "Purchase/SCM"),
    ("R&D/Engineering Design", "R&D/Engineering Design"),
    ("Sales / Business Development / Client servicing", "Sales / Business Development / Client servicing"),
    ("Security", "Security"),
    ("Shipping", "Shipping"),
    ("Software Development - ALL", "Software Development - ALL"),
    ("Teaching / Education / Language Specialist", "Teaching / Education / Language Specialist"),
    ("Telecom / IT Hardware / Tech. staff /Support", "Telecom / IT Hardware / Tech. staff /Support"),
    ("Top Management", "Top Management"),
    ("Any Other", "Any Other"),
)