JOB_LOCATION_CHOICES = (
    ('Vad', ('Vadodara')),
    ('Ahm', ('Ahmedabad')),
    ('Sur', ('Surat')),
    ('Raj', ('Rajkot')),
    ('Bha', ('Bharuch')),
    ('Ank', ('Ankleshwar')),
    ('Vap', ('Vapi')),
    ('Val', ('Valsad')),
    ('Ana', ('Anand')),
    ('Meh', ('Mehsana')),
    ('Bhav', ('Bhavnagar')),
    ('Juna', ('Junagadh')),
    ('Jam', ('Jamnagar')),
)
