# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookingForJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=10, verbose_name='Last Name')),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
