# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobopening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField(unique=True)),
                ('alternate_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('current_designation', models.CharField(max_length=50)),
                ('current_company_name', models.CharField(max_length=50)),
                ('present_location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50)),
                ('preferred_location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('notice_period', models.CharField(choices=[('Immediate', 'immediate'), ('7 Days', '7 Days'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], max_length=15)),
                ('skill', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100)),
                ('present_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('past_company_name', models.CharField(max_length=50)),
                ('past_designation', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('functional_area', models.CharField(choices=[('Accounting / Tax / Company', 'Accounting / Tax / Company'), ('Secretary / Auditing', 'Secretary / Auditing'), ('Agent', 'Agent'), ('Airlines / Ticketing / Travel / Reservation', 'Airlines / Ticketing / Travel / Reservation'), ('Analytics / Business Intelligences', 'Analytics / Business Intelligences'), ('Anchoring / TV / Films / Production', 'Anchoring / TV / Films / Production'), ('Architecture / Interior', 'Architecture / Interior'), ('Art Director/Web Design/ Graphic', 'Art Director/Web Design/ Graphic'), ('Banking / Insurance', 'Banking / Insurance'), ('Content / Editor / Generalist', 'Content / Editor / Generalist'), ('Corporate Planning / Consulting / Strategy', 'Corporate Planning / Consulting / Strategy'), ('Entrepreneur / Businessman/ Outside Management Consultant', 'Entrepreneur / Businessman/ Outside Management Consultant'), ('Import / Export', 'Import / Export'), ('Fashion', 'Fashion'), ('Front Office/Secretarial/Computer Operator', 'Front Office/Secretarial/Computer Operator'), ('Hotels/ Restaurant Manager', 'Hotels/ Restaurant Manager'), ('HR/Admin/PM/IT/Training', 'HR/Admin/PM/IT/Training'), ('ITES/BPO/Tele calling/Operations/ Customer Service', 'ITES/BPO/Tele calling/Operations/ Customer Service'), ('Legal /Law', 'Legal /Law'), ('Medical Professional/ Technician/ Healthcare Specialist', 'Medical Professional/ Technician/ Healthcare Specialist'), ('Mktg/Advtg/MR/Media Planning/PR/ Corp. Panning', 'Mktg/Advtg/MR/Media Planning/PR/Corp. Panning'), ('Packaging Development', 'Packaging Development'), ('Production/ Service Engineering/Manufacturing / Maintenance', 'Production/ Service Engineering/Manufacturing / Maintenance'), ('Project Management/Site Engineers', 'Project Management/Site Engineers'), ('Purchase/SCM', 'Purchase/SCM'), ('R&D/Engineering Design', 'R&D/Engineering Design'), ('Sales / Business Development / Client servicing', 'Sales / Business Development / Client servicing'), ('Security', 'Security'), ('Shipping', 'Shipping'), ('Software Development - ALL', 'Software Development - ALL'), ('Teaching / Education / Language Specialist', 'Teaching / Education / Language Specialist'), ('Telecom / IT Hardware / Tech. staff /Support', 'Telecom / IT Hardware / Tech. staff /Support'), ('Top Management', 'Top Management'), ('Any Other', 'Any Other')], max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('profile_summary', models.TextField()),
                ('resume_summary', models.TextField()),
                ('resume', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('feedback_update', models.CharField(choices=[('Resume Submitted', 'Resume Submitted'), ('profile shared', 'profile shared'), ('Shortlisted', 'Shortlisted'), ('Screening Rejected', 'Screening Rejected'), ('Interview Attended', 'Interview Attended'), ('Interview not attended', 'Interview not attended'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Salary Offered', 'Salary Offered'), ('Offered Accepted', 'Offered Accepted'), ('Offer rejected', 'Offer rejected'), ('Submit Documents', 'Submit Documents'), ('Joined', 'Joined')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReferCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('candidate_name', models.CharField(max_length=50, verbose_name='Candidate Name')),
                ('contact_number', models.IntegerField(unique=True, verbose_name='Primary Contact Number')),
                ('alternate_number', models.IntegerField(blank=True, verbose_name='Secondary Contact Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('current_designation', models.CharField(max_length=50, verbose_name='Present Designation')),
                ('current_company_name', models.CharField(max_length=50, verbose_name='Current Company')),
                ('present_location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50, verbose_name='Present Location')),
                ('preferred_location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50, verbose_name='Preferred Location')),
                ('experience', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Experience')),
                ('notice_period', models.CharField(choices=[('Immediate', 'immediate'), ('7 Days', '7 Days'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], max_length=15, verbose_name='Notice Period')),
                ('skill', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100)),
                ('present_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('functional_area', models.CharField(choices=[('Accounting / Tax / Company', 'Accounting / Tax / Company'), ('Secretary / Auditing', 'Secretary / Auditing'), ('Agent', 'Agent'), ('Airlines / Ticketing / Travel / Reservation', 'Airlines / Ticketing / Travel / Reservation'), ('Analytics / Business Intelligences', 'Analytics / Business Intelligences'), ('Anchoring / TV / Films / Production', 'Anchoring / TV / Films / Production'), ('Architecture / Interior', 'Architecture / Interior'), ('Art Director/Web Design/ Graphic', 'Art Director/Web Design/ Graphic'), ('Banking / Insurance', 'Banking / Insurance'), ('Content / Editor / Generalist', 'Content / Editor / Generalist'), ('Corporate Planning / Consulting / Strategy', 'Corporate Planning / Consulting / Strategy'), ('Entrepreneur / Businessman/ Outside Management Consultant', 'Entrepreneur / Businessman/ Outside Management Consultant'), ('Import / Export', 'Import / Export'), ('Fashion', 'Fashion'), ('Front Office/Secretarial/Computer Operator', 'Front Office/Secretarial/Computer Operator'), ('Hotels/ Restaurant Manager', 'Hotels/ Restaurant Manager'), ('HR/Admin/PM/IT/Training', 'HR/Admin/PM/IT/Training'), ('ITES/BPO/Tele calling/Operations/ Customer Service', 'ITES/BPO/Tele calling/Operations/ Customer Service'), ('Legal /Law', 'Legal /Law'), ('Medical Professional/ Technician/ Healthcare Specialist', 'Medical Professional/ Technician/ Healthcare Specialist'), ('Mktg/Advtg/MR/Media Planning/PR/ Corp. Panning', 'Mktg/Advtg/MR/Media Planning/PR/Corp. Panning'), ('Packaging Development', 'Packaging Development'), ('Production/ Service Engineering/Manufacturing / Maintenance', 'Production/ Service Engineering/Manufacturing / Maintenance'), ('Project Management/Site Engineers', 'Project Management/Site Engineers'), ('Purchase/SCM', 'Purchase/SCM'), ('R&D/Engineering Design', 'R&D/Engineering Design'), ('Sales / Business Development / Client servicing', 'Sales / Business Development / Client servicing'), ('Security', 'Security'), ('Shipping', 'Shipping'), ('Software Development - ALL', 'Software Development - ALL'), ('Teaching / Education / Language Specialist', 'Teaching / Education / Language Specialist'), ('Telecom / IT Hardware / Tech. staff /Support', 'Telecom / IT Hardware / Tech. staff /Support'), ('Top Management', 'Top Management'), ('Any Other', 'Any Other')], max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('candidate_referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidate_by', to=settings.AUTH_USER_MODEL)),
                ('refer_for_the_post_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobopening.Jobopening', verbose_name='Referred for the post of')),
            ],
        ),
    ]
