# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_date_created', models.DateTimeField(auto_created=True)),
                ('company', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=40)),
                ('company_profile', models.TextField()),
                ('company_location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50)),
                ('company_website', models.URLField(default=None, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='ReferClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, null=True)),
                ('client_name', models.CharField(max_length=70)),
                ('location', models.CharField(choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=50)),
                ('contact_person_name', models.CharField(max_length=50, verbose_name='Contact Name')),
                ('contact_number', models.PositiveIntegerField()),
                ('contact_email_id', models.EmailField(max_length=50)),
                ('position_required', models.CharField(max_length=500)),
                ('no_of_requirement', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
